service: tgb3

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.8
  memorySize: 256
  stage: prod
  region: us-east-1
  environment:
    CODES: ${file(./serverless.env.yml):CODES, ''}
    TELEGRAM_TOKEN: ${file(./serverless.env.yml):TELEGRAM_TOKEN, ''}
    TELEGRAM_CHAT_ID: ${file(./serverless.env.yml):TELEGRAM_CHAT_ID, ''}

functions:
  alert:
    handler: handler.alert

custom:
  pythonRequirements:
    dockerizePip: false
